spring:
  application:
    name: forum-hub

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

api:
  security:
    jwt:
      secret: ${JWT_SECRET}